services:
  - type: web
    name: sims-backend-api
    env: docker
    dockerContext: .
    plan: free
    # Sobreescribimos el comando del Dockerfile para arrancar el servidor HTTP
    # Render inyecta automáticamente la variable PORT
    buildCommand: "php artisan migrate --force" # Ejecutamos migraciones antes de arrancar
    startCommand: "php artisan serve --host=0.0.0.0 --port=$PORT" 
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        sync: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_URL
        fromDatabase:
          name: sims-db
          property: connectionString

databases:
  - name: sims-db
    plan: free
    databaseName: project_sims_landlord
    user: admin_sims
