services:
  - type: web
    name: sims-backend-api
    env: docker
    dockerContext: .
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true # Render generará una clave automáticamente
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_URL # Laravel usará esta URL que contiene host, puerto, db, usuario y password
        fromService:
          name: sims-db
          type: psql
          property: connectionString

databases:
  - name: sims-db
    plan: free
    databaseName: project_sims_landlord
    user: admin_sims
