---
config:
  layout: elk
---
erDiagram
	direction TB

	SAAS_COMPANY {
		UUID id PK
		varchar nombre
		varchar dominio
		timestamptz creado_en
	}

	SAAS_USUARIOS {
		UUID id PK
		UUID saas_company_id FK
		varchar email
		varchar nombre_completo
		varchar rol_global
		boolean activo
	}

	TENANTS {
		UUID id PK
		UUID saas_company_id FK
		varchar nombre
		varchar dominio
		varchar estado
		timestamptz creado_en
	}

	PLANES {
		UUID id PK
		varchar nombre
		text descripcion
		boolean activo
	}

	PLAN_VERSIONES {
		UUID id PK
		UUID plan_id FK
		int version
		numeric precio
		varchar billing_cycle
		jsonb limites
		jsonb features
		boolean activo
	}

	SUSCRIPCIONES {
		UUID id PK
		UUID tenant_id FK
		UUID plan_version_id FK
		timestamptz inicio
		timestamptz fin
		varchar estado
		int seats
	}

	FACTURAS {
		UUID id PK
		UUID tenant_id FK
		UUID suscripcion_id FK
		numeric importe
		varchar moneda
		varchar estado
		timestamptz emitida_en
		timestamptz pagada_en
	}

	PAGOS {
		UUID id PK
		UUID factura_id FK
		varchar proveedor
		varchar referencia
		numeric importe
		timestamptz pagado_en
	}

	LIMITES_USO {
		UUID id PK
		UUID tenant_id FK
		varchar recurso
		int limite
		int usado
		timestamptz periodo_inicio
		timestamptz periodo_fin
	}

	LOGS_SAAS {
		bigserial id PK
		UUID saas_user_id FK
		UUID tenant_id FK
		varchar accion
		jsonb metadata
		timestamptz ts
	}

	SAAS_COMPANY ||--o{ SAAS_USUARIOS : emplea
	SAAS_COMPANY ||--o{ TENANTS : gestiona

	PLANES ||--o{ PLAN_VERSIONES : tiene
	PLAN_VERSIONES ||--o{ SUSCRIPCIONES : define

	TENANTS ||--o{ SUSCRIPCIONES : contrata
	TENANTS ||--o{ FACTURAS : recibe
	FACTURAS ||--o{ PAGOS : liquida
	TENANTS ||--o{ LIMITES_USO : consume

	SAAS_USUARIOS ||--o{ LOGS_SAAS : audita
	TENANTS ||--o{ LOGS_SAAS : afectado
