name: Test & Build Release - Backend

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite
          coverage: none

      - name: Install Dependencies
        run: composer install --prefer-dist --no-interaction

      - name: Copy .env.example
        run: cp .env.example .env

      - name: Generate Key
        run: php artisan key:generate

      - name: Run Tests
        run: php artisan test

  release:
    needs: test # Solo se ejecuta si los tests pasan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Pack Docker Image
        run: |
          docker build -t sims-backend:latest .
          docker save -o sims-backend-latest.tar sims-backend:latest

      - name: Create or Update Latest Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Latest Production Build
          files: sims-backend-latest.tar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
